CREATE TABLE ROLE (
    ID          NUMERIC PRIMARY KEY,
    NAME        VARCHAR(256)  NOT NULL
);

CREATE TABLE USERS (
    ID          NUMERIC PRIMARY KEY,
    SURNAME     VARCHAR(256) NOT NULL,
    NAME        VARCHAR(256) NOT NULL,
    PATRONYMIC  VARCHAR(256),
    EMAIL       VARCHAR(48),
    PHOTO_PATH  VARCHAR(256),
    PHONE       VARCHAR(48),
    LOGIN       VARCHAR(48),
    ROLE_ID     NUMERIC NOT NULL,
    PASSWORD    VARCHAR(256) NOT NULL,
    FOREIGN KEY (ROLE_ID)    REFERENCES ROLE(ID)
);